// frontend-vue-ts/src/views/auth/login.vue
<script setup lang="ts">
//import ref dan reactive dari vue
import { ref, reactive } from "vue";

//import useRouter dari vue-router
import { useRouter } from "vue-router";

//import js cookie
import Cookies from "js-cookie";

//import composable useLogin
import { useLogin } from "../../composables/auth/useLogin";

// Tipe untuk error validasi
interface ValidationErrors {
    [key: string]: string;
}

// Router
const router = useRouter();

// Composable login
const { mutate, isPending } = useLogin();

// Form state
const username = ref<string>("");
const password = ref<string>("");

// Error state
const errors = reactive<ValidationErrors>({});

// Handle submit form
const handleLogin = (e: Event) => {
    e.preventDefault();

    //call mutasi login
    mutate(
        { username: username.value, password: password.value },
        {
            onSuccess: (data: any) => {
                //set cookie token
                Cookies.set("token", data.data.token);

                //set cookie user
                Cookies.set(
                    "user",
                    JSON.stringify({
                        id: data.data.id,
                        name: data.data.name,
                        username: data.data.username,
                        email: data.data.email,
                    })
                );

                //redirect ke dashboard
                router.push("/admin/dashboard");
            },
            onError: (error: any) => {
                //assign errors, error.response.data.errors)
                Object.assign(errors, error.response.data.errors);
            },
        }
    );
};
</script>

<template>
    <div class="row justify-content-center mt-5">
        <div class="col-md-4">
            <div class="card border-0 rounded-4 shadow-sm">
                <div class="card-body">
                    <h4 class="fw-bold text-center">LOGIN</h4>
                    <hr />
                    <div
                        v-if="errors.Error"
                        class="alert alert-danger mt-2 rounded-4"
                    >
                        Username or Password is incorrect
                    </div>
                    <form @submit="handleLogin">
                        <div class="form-group mb-3">
                            <label class="mb-1 fw-bold">Username</label>
                            <input
                                v-model="username"
                                type="text"
                                class="form-control"
                                placeholder="Username"
                            />
                            <div
                                v-if="errors.Username"
                                class="alert alert-danger mt-2 rounded-4"
                            >
                                {{ errors.Username }}
                            </div>
                        </div>

                        <div class="form-group mb-3">
                            <label class="mb-1 fw-bold">Password</label>
                            <input
                                v-model="password"
                                type="password"
                                class="form-control"
                                placeholder="Password"
                            />
                            <div
                                v-if="errors.Password"
                                class="alert alert-danger mt-2 rounded-4"
                            >
                                {{ errors.Password }}
                            </div>
                        </div>

                        <button
                            type="submit"
                            class="btn btn-primary w-100 rounded-4"
                            :disabled="isPending"
                        >
                            {{ isPending ? "Loading..." : "LOGIN" }}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</template>

// frontend-react-ts/src/views/auth/login.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
// import FC from react
import type { FC } from 'react';
import { useState, useContext } from 'react';
import type { FormEvent } from 'react';

//import hook useNavigate from react router
import { useNavigate } from "react-router";

//import custom  hook useLogin from hooks
import { useLogin } from "../../hooks/auth/useLogin";

//import js-cookie
import Cookies from 'js-cookie'

//import context
import { AuthContext } from '../../context/AuthContext';

//interface for validation errors
interface ValidationErrors {
    [key: string]: string;
}

export const Login: FC = () => {

    //initialize navigate
    const navigate = useNavigate();

    //initialize useLogin
    const { mutate, isPending } = useLogin();

    //destruct auth context "setIsAuthenticated"
    const { setIsAuthenticated } = useContext(AuthContext)!;

    //define state
    const [username, setUsername] = useState<string>('');
    const [password, setPassword] = useState<string>('');

    //define state for errors
    const [errors, setErrors] = useState<ValidationErrors>({});

    // Handle submit form
    const handleLogin = async (e: FormEvent) => {
        e.preventDefault();

        // Call the login mutation
        mutate({
            username,
            password
        }, {
            onSuccess: (data: any) => {

                //set token to cookie
                Cookies.set('token', data.data.token);

                //set user to cookie
                Cookies.set('user', JSON.stringify({
                    id: data.data.id,
                    name: data.data.name,
                    username: data.data.username,
                    email: data.data.email
                }));

                //set isAuthenticated to true
                setIsAuthenticated(true);

                // Redirect to dashboard page
                navigate('/admin/dashboard');
            },
            onError: (error: any) => {

                //set errors to state "errors"
                setErrors(error.response.data.errors);
            }
        })
    }

    return (
        <div className="row justify-content-center mt-5">
            <div className="col-md-4">
                <div className="card border-0 rounded-4 shadow-sm">
                    <div className="card-body">
                        <h4 className='fw-bold text-center'>LOGIN</h4>
                        <hr />
                        {errors.Error && <div className="alert alert-danger mt-2 rounded-4">Username or Password is incorrect</div>}
                        <form onSubmit={handleLogin}>
                            <div className="form-group mb-3">
                                <label className="mb-1 fw-bold">Username</label>
                                <input type="text" value={username} onChange={(e) => setUsername(e.target.value)} className="form-control" placeholder="Username" />
                                {errors.Username && <div className="alert alert-danger mt-2 rounded-4">{errors.Username}</div>}
                            </div>

                            <div className="form-group mb-3">
                                <label className="mb-1 fw-bold">Password</label>
                                <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="form-control"
                                    placeholder="Password" />
                                {errors.Password && <div className="alert alert-danger mt-2 rounded-4">{errors.Password}</div>}
                            </div>
                            <button type="submit" className="btn btn-primary w-100 rounded-4" disabled={isPending}>
                                {isPending ? 'Loading...' : 'LOGIN'}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default Login;
