// frontend-vue-ts/src/views/auth/register.vue
<script setup lang="ts">
//import ref dan reactive dari vue
import { ref, reactive } from "vue";

//import useRouter dari vue-router
import { useRouter } from "vue-router";

//import composable useRegister
import { useRegister } from "../../composables/auth/useRegister";

//interface untuk error
interface ValidationErrors {
    [key: string]: string;
}

//inisialisasi router
const router = useRouter();

// form state
const name = ref<string>("");
const username = ref<string>("");
const email = ref<string>("");
const password = ref<string>("");

// error state
const errors = reactive<ValidationErrors>({});

// custom composable
const { mutate, isPending } = useRegister();

const handleRegister = (e: Event) => {
    e.preventDefault();

    //call mutate function from useRegister
    mutate(
        {
            name: name.value,
            username: username.value,
            email: email.value,
            password: password.value,
        },
        {
            onSuccess: () => {
                //redirect to login page after success
                router.push("/login");
            },
            onError: (error: any) => {
                //assign errors with the error response
                Object.assign(errors, error.response.data.errors);
            },
        }
    );
};
</script>

<template>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card border-0 rounded-4 shadow-sm">
                <div class="card-body">
                    <h4 class="fw-bold text-center">REGISTER</h4>
                    <hr />
                    <form @submit.prevent="handleRegister">
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <div class="form-group">
                                    <label class="mb-1 fw-bold"
                                        >Full Name</label
                                    >
                                    <input
                                        v-model="name"
                                        type="text"
                                        class="form-control"
                                        placeholder="Full Name"
                                    />
                                    <div
                                        v-if="errors.Name"
                                        class="alert alert-danger mt-2 rounded-4"
                                    >
                                        {{ errors.Name }}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 mb-3">
                                <div class="form-group">
                                    <label class="mb-1 fw-bold">Username</label>
                                    <input
                                        v-model="username"
                                        type="text"
                                        class="form-control"
                                        placeholder="Username"
                                    />
                                    <div
                                        v-if="errors.Username"
                                        class="alert alert-danger mt-2 rounded-4"
                                    >
                                        {{ errors.Username }}
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <div class="form-group">
                                    <label class="mb-1 fw-bold"
                                        >Email address</label
                                    >
                                    <input
                                        v-model="email"
                                        type="email"
                                        class="form-control"
                                        placeholder="Email Address"
                                    />
                                    <div
                                        v-if="errors.Email"
                                        class="alert alert-danger mt-2 rounded-4"
                                    >
                                        {{ errors.Email }}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6 mb-3">
                                <div class="form-group">
                                    <label class="mb-1 fw-bold">Password</label>
                                    <input
                                        v-model="password"
                                        type="password"
                                        class="form-control"
                                        placeholder="Password"
                                    />
                                    <div
                                        v-if="errors.Password"
                                        class="alert alert-danger mt-2 rounded-4"
                                    >
                                        {{ errors.Password }}
                                    </div>
                                </div>
                            </div>
                        </div>

                        <button
                            type="submit"
                            class="btn btn-primary w-100 rounded-4"
                            :disabled="isPending"
                        >
                            {{ isPending ? "Loading..." : "REGISTER" }}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</template>

// frontend-react-ts/src/views/auth/register.tsx
// import FC from react
import type { FC } from 'react';
import { useState } from 'react';
import type { FormEvent } from 'react';

//import hook useNavigate from react router
import { useNavigate } from "react-router";

//import custom  hook useRegister from hooks
import { useRegister } from "../../hooks/auth/useRegister";

//interface for validation errors
interface ValidationErrors {
    [key: string]: string;
}

const Register: FC = () => {

    //initialize navigate
    const navigate = useNavigate();

    //initialize useRegister
    const { mutate, isPending } = useRegister();

    //define state
    const [name, setName] = useState<string>('');
    const [username, setUsername] = useState<string>('');
    const [email, setEmail] = useState<string>('');
    const [password, setPassword] = useState<string>('');

    //define state for errors
    const [errors, setErrors] = useState<ValidationErrors>({});

    // Handle submit form
    const handleRegister = async (e: FormEvent) => {
        e.preventDefault();

        // Call the register mutation
        mutate({
            name,
            username,
            email,
            password
        }, {
            onSuccess: () => {

                // Redirect to login page
                navigate('/login');
            },
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            onError: (error: any) => {
                //set errors to state "errors"
                setErrors(error.response.data.errors);
            }
        })

    }

    return (
        <div className="row justify-content-center">
            <div className="row justify-content-center">
                <div className="col-md-6">
                    <div className="card border-0 rounded-4 shadow-sm">
                        <div className="card-body">
                            <h4 className='fw-bold text-center'>REGISTER</h4>
                            <hr />
                            <form onSubmit={handleRegister}>
                                <div className="row">
                                    <div className="col-md-12 mb-3">
                                        <div className="form-group">
                                            <label className="mb-1 fw-bold">Nama</label>
                                            <input type="text" value={name} onChange={(e) => setName(e.target.value)} className="form-control"
                                                placeholder="Nama" />
                                            {errors.Name && <div className="alert alert-danger mt-2 rounded-4">{errors.Name}</div>}
                                        </div>
                                    </div>
                                    <div className="col-md-12 mb-3">
                                        <div className="form-group">
                                            <label className="mb-1 fw-bold">Username</label>
                                            <input type="text" value={username} onChange={(e) => setUsername(e.target.value)} className="form-control" placeholder="Username" />
                                            {errors.Username && <div className="alert alert-danger mt-2 rounded-4">{errors.Username}</div>}
                                        </div>
                                    </div>
                                </div>

                                <div className="row">
                                    <div className="col-md-12 mb-3">
                                        <div className="form-group">
                                            <label className="mb-1 fw-bold">Email</label>
                                            <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="form-control"
                                                placeholder="Email" />
                                            {errors.Email && <div className="alert alert-danger mt-2 rounded-4">{errors.Email}</div>}
                                        </div>
                                    </div>
                                    <div className="col-md-12 mb-3">
                                        <div className="form-group">
                                            <label className="mb-1 fw-bold">Password</label>
                                            <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="form-control"
                                                placeholder="Password" />
                                            {errors.Password && <div className="alert alert-danger mt-2 rounded-4">{errors.Password}</div>}
                                        </div>
                                    </div>
                                </div>
                                <button type="submit" className="btn btn-primary w-100 rounded-none" disabled={isPending}>
                                    {isPending ? 'Loading...' : 'REGISTER'}
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default Register;
