// frontend-vue-ts/src/views/home/index.vue
<script setup lang="ts"></script>

<template>
    <div class="p-5 mb-4 bg-light rounded-3 shadow-sm">
        <div class="container-fluid py-5">
            <h1 class="display-5 fw-bold">FULLTSACK DEVELOPER</h1>
            <p class="col-md-12 fs-4">
                Belajar FullStack Developer dengan Golang dan Vue 3 TypeScript
                di codopro.id
            </p>
            <hr />
            <router-link to="/register" class="btn btn-primary btn-lg me-3"
                >Register</router-link
            >
            <router-link to="/login" class="btn btn-secondary btn-lg"
                >Login</router-link
            >
        </div>
    </div>
</template>

// frontend-react-ts/src/views/home/index.tsx
// import FC from react
import type { FC } from 'react';

// import Link from react-router
import { Link } from 'react-router';

const Home: FC = () => {
    return (
        <div className="p-5 mb-4 bg-light rounded-5 shadow-sm">
            <div className="container-fluid py-5">
                <h1 className="display-5 fw-bold">FULLTSACK DEVELOPER</h1>
                <p className="col-md-12 fs-4">Belajar FullStack Developer dengan Golang dan React TypeScript di codopro.id</p>
                <hr />
                <Link to="/register" className="btn btn-primary btn-lg me-3">REGISTER</Link>
                <Link to="/login" className="btn btn-secondary btn-lg">LOGIN</Link>
            </div>
        </div>
    )
}

export default Home;
