// frontend-react-ts/src/views/admin/users/create.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
//import FC from react
import { type FC, useState, type FormEvent } from "react";

//import SidebarMenu
import SidebarMenu from '../../../components/SidebarMenu';

//import useNavigate and Link from react-router
import { useNavigate, Link } from 'react-router';

//import custom hook useUserCreate
import { useUserCreate } from '../../../hooks/user/useUserCreate';
import InputLabel from "../../../components/moleculles/InputLabel";
import ErrorAlert from "../../../components/moleculles/ErrorAlert";

//interface for validation errors
interface ValidationErrors {
    [key: string]: string;
}

const UserCreate: FC = () => {

    //initialize useNavigate
    const navigate = useNavigate();

    //define state user
    const [name, setName] = useState<string>('');
    const [username, setUsername] = useState<string>('');
    const [email, setEmail] = useState<string>('');
    const [password, setPassword] = useState<string>('');

    //define state errors
    const [errors, setErrors] = useState<ValidationErrors>({});

    // Inisialisasi useUserCreate
    const { mutate, isPending } = useUserCreate();

    // Handle submit form
    const storeUser = async (e: FormEvent) => {
        e.preventDefault();

        // Call the user create mutation
        mutate({
            name,
            username,
            email,
            password
        }, {
            onSuccess: () => {

                // Redirect to users index
                navigate('/admin/users');
            },
            onError: (error: any) => {

                //set errors to state "errors"
                setErrors(error.response.data.errors);
            }
        })
    }

    return (
        <div className="container mt-5 mb-5">
            <div className="row">
                <div className="col-md-3">
                    <SidebarMenu />
                </div>
                <div className="col-md-9">
                    <div className="card border-0 rounded-4 shadow-sm">
                        <div className="card-header bg-white">
                            Tambah Data
                        </div>
                        <div className="card-body">
                            <form onSubmit={storeUser}>
                                <div className="form-group mb-3">
                                    <InputLabel htmlFor="name" label="Nama" isRequired={true} />
                                    <input type="text" value={name} id="name" onChange={(e) => setName(e.target.value)} className="form-control" placeholder="Nama" />
                                    {errors.Name && <ErrorAlert error={errors.Name} />}
                                </div>
                                <div className="form-group mb-3">
                                    <InputLabel htmlFor="username" label="Username" isRequired={true} />
                                    <input type="text" value={username} id="username" onChange={(e) => setUsername(e.target.value)} className="form-control" placeholder="Username" />
                                    {errors.Username && <ErrorAlert error={errors.Username} />}
                                </div>
                                <div className="form-group mb-3">
                                    <InputLabel htmlFor="email" label="Email" isRequired={true} />
                                    <input type="email" value={email} id="email" onChange={(e) => setEmail(e.target.value)} className="form-control" placeholder="Email" />
                                    {errors.Email && <ErrorAlert error={errors.Email} />}
                                </div>
                                <div className="form-group mb-3">
                                    <InputLabel htmlFor="password" label="Password" isRequired={true} />
                                    <input type="password" value={password} id="password" onChange={(e) => setPassword(e.target.value)} className="form-control" placeholder="Password" />
                                    {errors.Password && <ErrorAlert error={errors.Password} />}
                                </div>
                                <div className="btn-group">
                                    <button type="submit" className="btn btn-sm btn-primary shadow-sm border-0" disabled={isPending}>
                                        {isPending ? 'Sedang Menyimpan...' : 'Simpan'}
                                    </button>
                                    <Link to="/admin/users" className="btn btn-sm btn-secondary shadow-sm border-0">Batal</Link>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div >
    )
}

export default UserCreate

// frontend-vue-ts/src/views/admin/users/create.vue
<script setup lang="ts">
//import ref dan reactive dari vue
import { ref, reactive } from "vue";

//import useRouter dari vue-router
import { useRouter } from "vue-router";

//import component SidebarMenu
import SidebarMenu from "../../../components/SidebarMenu.vue";

//import composable useUserCreate
import { useUserCreate } from "../../../composables/user/useUserCreate";

// Router instance
const router = useRouter();

// Form state
const name = ref<string>("");
const username = ref<string>("");
const email = ref<string>("");
const password = ref<string>("");

// Validation errors
const errors = reactive<Record<string, string>>({});

// Mutation
const { mutate, isPending } = useUserCreate();

// Handle form submit
const storeUser = (e: Event) => {
    e.preventDefault();

    // Call user create mutation
    mutate(
        {
            name: name.value,
            username: username.value,
            email: email.value,
            password: password.value,
        },
        {
            onSuccess: () => {
                // Redirect to users index
                router.push("/admin/users");
            },
            onError: (error: any) => {
                // Assign validation errors to the errors object
                Object.assign(errors, error.response.data.errors);
            },
        }
    );
};
</script>

<template>
    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-md-3">
                <SidebarMenu />
            </div>
            <div class="col-md-9">
                <div class="card border-0 rounded-4 shadow-sm">
                    <div class="card-header">Tambah User</div>
                    <div class="card-body">
                        <form @submit="storeUser">
                            <div class="form-group mb-3">
                                <label class="mb-1 fw-bold">Nama</label>
                                <input
                                    type="text"
                                    v-model="name"
                                    class="form-control"
                                    placeholder="Nama"
                                />
                                <div
                                    v-if="errors.Name"
                                    class="alert alert-danger mt-2"
                                >
                                    {{ errors.Name }}
                                </div>
                            </div>

                            <div class="form-group mb-3">
                                <label class="mb-1 fw-bold">Username</label>
                                <input
                                    type="text"
                                    v-model="username"
                                    class="form-control"
                                    placeholder="Username"
                                />
                                <div
                                    v-if="errors.Username"
                                    class="alert alert-danger mt-2"
                                >
                                    {{ errors.Username }}
                                </div>
                            </div>

                            <div class="form-group mb-3">
                                <label class="mb-1 fw-bold">Email</label>
                                <input
                                    type="email"
                                    v-model="email"
                                    class="form-control"
                                    placeholder="Email"
                                />
                                <div
                                    v-if="errors.Email"
                                    class="alert alert-danger mt-2"
                                >
                                    {{ errors.Email }}
                                </div>
                            </div>

                            <div class="form-group mb-3">
                                <label class="mb-1 fw-bold">Password</label>
                                <input
                                    type="password"
                                    v-model="password"
                                    class="form-control"
                                    placeholder="Password"
                                />
                                <div
                                    v-if="errors.Password"
                                    class="alert alert-danger mt-2"
                                >
                                    {{ errors.Password }}
                                </div>
                            </div>
                            <div class="btn-group">
                                <button
                                    type="submit"
                                    class="btn btn-sm btn-primary shadow-sm border-0"
                                    :disabled="isPending"
                                >
                                    {{
                                        isPending
                                            ? "Sedang Menyimpan..."
                                            : "Simpan"
                                    }}
                                </button>

                                <router-link
                                    to="/admin/users"
                                    class="btn btn-sm btn-secondary shadow-sm border-0"
                                >
                                    Batal
                                </router-link>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>
