// frontend-react-ts/src/views/admin/users/edit.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
//import FC from react
import { type FC, useState, useEffect, type FormEvent } from "react";

//import SidebarMenu
import SidebarMenu from '../../../components/SidebarMenu';

//import useNavigate, useParams and Link from react-router
import { useNavigate, useParams, Link } from 'react-router';

//import custom hook useUserByById
import { useUserById } from '../../../hooks/user/useUserById';

//import custom hook useUserUpdate
import { useUserUpdate } from '../../../hooks/user/useUserUpdate';

//interface for validation errors
interface ValidationErrors {
    [key: string]: string;
}

const UserEdit: FC = () => {

    //initialize useNavigate
    const navigate = useNavigate();

    //initialize useParams
    const { id } = useParams();

    //define state user
    const [name, setName] = useState<string>('');
    const [username, setUsername] = useState<string>('');
    const [email, setEmail] = useState<string>('');
    const [password, setPassword] = useState<string>('');

    //define state errors
    const [errors, setErrors] = useState<ValidationErrors>({});

    // inisialisasi useUSerById
    const { data: user } = useUserById(Number(id));

    //set data user to state
    useEffect(() => {

        if (user) {
            setName(user.name);
            setUsername(user.username);
            setEmail(user.email);
        }
    }, [user]);

    // Inisialisasi useUserUpdate
    const { mutate, isPending } = useUserUpdate();

    // Handle submit form
    const updateUser = async (e: FormEvent) => {
        e.preventDefault();

        // Call the user update mutation
        mutate({
            id: Number(id),
            data: {
                name,
                username,
                email,
                password
            }
        }, {
            onSuccess: () => {

                // Redirect to users index
                navigate('/admin/users');

            },
            onError: (error: any) => {

                //set errors to state "errors"
                setErrors(error.response.data.errors);

            }
        })
    }

    return (
        <div className="container mt-5 mb-5">
            <div className="row">
                <div className="col-md-3">
                    <SidebarMenu />
                </div>
                <div className="col-md-9">
                    <div className="card border-0 rounded-4 shadow-sm">
                        <div className="card-header">
                            EDIT USER
                        </div>
                        <div className="card-body">
                            <form onSubmit={updateUser}>

                                <div className="form-group mb-3">
                                    <label className="mb-1 fw-bold">Full Name</label>
                                    <input type="text" value={name} onChange={(e) => setName(e.target.value)} className="form-control" placeholder="Full Name" />
                                    {errors.Name && <div className="alert alert-danger mt-2 rounded-4">{errors.Name}</div>}
                                </div>

                                <div className="form-group mb-3">
                                    <label className="mb-1 fw-bold">Username</label>
                                    <input type="text" value={username} onChange={(e) => setUsername(e.target.value)} className="form-control" placeholder="Username" />
                                    {errors.Username && <div className="alert alert-danger mt-2 rounded-4">{errors.Username}</div>}
                                </div>

                                <div className="form-group mb-3">
                                    <label className="mb-1 fw-bold">Email address</label>
                                    <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="form-control"
                                        placeholder="Email Address" />
                                    {errors.Email && <div className="alert alert-danger mt-2 rounded-4">{errors.Email}</div>}
                                </div>

                                <div className="form-group mb-3">
                                    <label className="mb-1 fw-bold">Password</label>
                                    <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="form-control"
                                        placeholder="Password" />
                                    {errors.Password && <div className="alert alert-danger mt-2 rounded-4">{errors.Password}</div>}
                                </div>

                                <button type="submit" className="btn btn-md btn-primary rounded-4 shadow-sm border-0" disabled={isPending}>
                                    {isPending ? 'Updating...' : 'Update'}
                                </button>

                                <Link to="/admin/users" className="btn btn-md btn-secondary rounded-4 shadow-sm border-0 ms-2">Cancel</Link>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div >
    )
}

export default UserEdit

// frontend-vue-ts/src/views/admin/users/edit.vue
<script setup lang="ts">
//import ref, reactive dan watchEffect dari vue
import { ref, reactive, watchEffect } from "vue";

//import useRoute dan useRouter dari vue-router
import { useRoute, useRouter } from "vue-router";

//import component SidebarMenu
import SidebarMenu from "../../../components/SidebarMenu.vue";

//import composable useUserById
import { useUserById } from "../../../composables/user/useUserById";

//import composable useUserUpdate
import { useUserUpdate } from "../../../composables/user/useUserUpdate";

// inisialisasi route dan router
const route = useRoute();
const router = useRouter();

// Ambil ID dari route param
const id = Number(route.params.id);

// Form state
const name = ref<string>("");
const username = ref<string>("");
const email = ref<string>("");
const password = ref<string>("");

// Validation errors
const errors = reactive<Record<string, string>>({});

// Fetch user by ID
const { data: user } = useUserById(id);

// Isi form dari data user
watchEffect(() => {
    if (user.value) {
        name.value = user.value.name;
        username.value = user.value.username;
        email.value = user.value.email;
    }
});

// Mutation
const { mutate, isPending } = useUserUpdate();

// Handle form submit
const updateUser = (e: Event) => {
    e.preventDefault();

    // Call user update mutation
    mutate(
        {
            id,
            data: {
                name: name.value,
                username: username.value,
                email: email.value,
                password: password.value,
            },
        },
        {
            onSuccess: () => {
                // Redirect to users index
                router.push("/admin/users");
            },
            onError: (error: any) => {
                // Assign validation errors to the errors object
                Object.assign(errors, error.response.data.errors);
            },
        }
    );
};
</script>

<template>
    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-md-3">
                <SidebarMenu />
            </div>
            <div class="col-md-9">
                <div class="card border-0 rounded-4 shadow-sm">
                    <div class="card-header">Edit User</div>
                    <div class="card-body">
                        <form @submit="updateUser">
                            <div class="form-group mb-3">
                                <label class="mb-1 fw-bold">Nama</label>
                                <input
                                    type="text"
                                    v-model="name"
                                    class="form-control"
                                    placeholder="Nama"
                                />
                                <div
                                    v-if="errors.Name"
                                    class="alert alert-danger mt-2"
                                >
                                    {{ errors.Name }}
                                </div>
                            </div>

                            <div class="form-group mb-3">
                                <label class="mb-1 fw-bold">Username</label>
                                <input
                                    type="text"
                                    v-model="username"
                                    class="form-control"
                                    placeholder="Username"
                                />
                                <div
                                    v-if="errors.Username"
                                    class="alert alert-danger mt-2"
                                >
                                    {{ errors.Username }}
                                </div>
                            </div>

                            <div class="form-group mb-3">
                                <label class="mb-1 fw-bold">Email</label>
                                <input
                                    type="email"
                                    v-model="email"
                                    class="form-control"
                                    placeholder="Email"
                                />
                                <div
                                    v-if="errors.Email"
                                    class="alert alert-danger mt-2"
                                >
                                    {{ errors.Email }}
                                </div>
                            </div>

                            <div class="form-group mb-3">
                                <label class="mb-1 fw-bold">Password</label>
                                <input
                                    type="password"
                                    v-model="password"
                                    class="form-control"
                                    placeholder="Password"
                                />
                                <div
                                    v-if="errors.Password"
                                    class="alert alert-danger mt-2"
                                >
                                    {{ errors.Password }}
                                </div>
                            </div>
                            <div class="btn-group">
                                <button
                                    type="submit"
                                    class="btn btn-sm btn-primary shadow-sm border-0"
                                    :disabled="isPending"
                                >
                                    {{
                                        isPending
                                            ? "Sedang Menyimpan..."
                                            : "Simpan"
                                    }}
                                </button>

                                <router-link
                                    to="/admin/users"
                                    class="btn btn-sm btn-secondary shadow-sm border-0"
                                >
                                    Batal
                                </router-link>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>
