// frontend-react-ts/src/views/admin/users/index.tsx
//import FC from react
import { type FC } from "react";

//import SidebarMenu
import SidebarMenu from '../../../components/SidebarMenu';

//import Link from react-route
import { Link } from "react-router";

//import custom hook useUsers and interface User
import { useUsers, type User } from "../../../hooks/user/useUsers";

import { useUserDelete } from "../../../hooks/user/useUserDelete";
import { useQueryClient } from "@tanstack/react-query";

const UsersIndex: FC = () => {

    // get users from useUsers
    const { data: users, isLoading, isError, error } = useUsers();

    const queryClient = useQueryClient();

    //initialize useUserDelete
    const { mutate, isPending } = useUserDelete();
    //handle delete user
    const handleDelete = (id: number) => {
        if (confirm("Are you sure you want to delete this user?")) {

            //call useUserDelete
            mutate(id, {
                onSuccess: () => {
                    //refetch data
                    queryClient.invalidateQueries({ queryKey: ['users'] });
                }
            });
        }
    }
    return (
        <div className="container mt-5 mb-5">
            <div className="row">
                <div className="col-md-3">
                    <SidebarMenu />
                </div>
                <div className="col-md-9">
                    <div className="card border-0 rounded-0 shadow-sm">
                        <div className="card-header d-flex justify-content-between align-items-center">
                            <span>Data User</span>
                            <Link to="/admin/users/create" className="btn btn-sm btn-primary shadow-sm border-0">Tambah Data</Link>
                        </div>
                        <div className="card-body">

                            {/* Loading State */}
                            {isLoading && (
                                <div className="alert alert-info text-center">Loading...</div>
                            )}

                            {/* Error State */}
                            {isError && (
                                <div className="alert alert-danger text-center">
                                    Error: {error.message}
                                </div>
                            )}

                            <table className="table table-bordered">
                                <thead className="bg-dark text-white">
                                    <tr>
                                        <th scope="col">Nama</th>
                                        <th scope="col">Username</th>
                                        <th scope="col">Email</th>
                                        <th scope="col" style={{ width: "20%" }}>Opsi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {
                                        users?.map((user: User) => (
                                            <tr key={user.id}>
                                                <td>{user.name}</td>
                                                <td>{user.username}</td>
                                                <td>{user.email}</td>
                                                <td className="text-center">
                                                    <div className="btn-group">
                                                        <Link to={`/admin/users/edit/${user.id}`} className="btn btn-sm btn-primary shadow-sm border-0">Edit</Link>
                                                        <button onClick={() => handleDelete(user.id)} disabled={isPending} className="btn btn-sm btn-danger shadow-sm border-0">
                                                            {isPending ? 'Sedang Menghapus...' : 'Hapus'}
                                                        </button>
                                                    </div>

                                                </td>
                                            </tr>
                                        ))
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default UsersIndex

// frontend-vue-ts/src/views/admin/users/index.vue
<script setup lang="ts">
//import useQueryClient dari '@tanstack/vue-query'
import { useQueryClient } from "@tanstack/vue-query";
// import composable useUsers
import { useUsers } from "../../../composables/user/useUsers";

// import composable useUserDelete
import { useUserDelete } from "../../../composables/user/useUserDelete";

// import SidebarMenu component
import SidebarMenu from "../../../components/SidebarMenu.vue";

// initialize query client
const queryClient = useQueryClient();

// Get users
const { data: users, isLoading, isError, error } = useUsers();

// // User delete composable
const { mutate, isPending } = useUserDelete();

// Handle delete
const handleDelete = (id: number) => {
    if (confirm("Are you sure you want to delete this user?")) {
        // Call delete user mutation
        mutate(id, {
            onSuccess: () => {
                // Invalidate users query to refresh the list
                queryClient.invalidateQueries({ queryKey: ["users"] });
            },
        });
    }
};
</script>

<template>
    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-md-3">
                <SidebarMenu />
            </div>
            <div class="col-md-9">
                <div class="card border-0 shadow-sm">
                    <div
                        class="card-header d-flex justify-content-between align-items-center"
                    >
                        <span>Data User</span>
                        <router-link
                            to="/admin/users/create"
                            class="btn btn-sm btn-primary shadow-sm border-0"
                        >
                            Tambah Data
                        </router-link>
                    </div>
                    <div class="card-body">
                        <div
                            v-if="isLoading"
                            class="alert alert-info text-center"
                        >
                            Loading...
                        </div>

                        <div
                            v-if="isError"
                            class="alert alert-danger text-center"
                        >
                            Error: {{ error?.message }}
                        </div>

                        <table v-if="users" class="table table-bordered">
                            <thead class="bg-dark text-white">
                                <tr>
                                    <th>Nama</th>
                                    <th>Username</th>
                                    <th>Email</th>
                                    <th style="width: 20%">Opsi</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr v-for="user in users" :key="user.id">
                                    <td>{{ user.name }}</td>
                                    <td>{{ user.username }}</td>
                                    <td>{{ user.email }}</td>
                                    <td class="text-center">
                                        <div class="btn-group">
                                            <router-link
                                                :to="`/admin/users/edit/${user.id}`"
                                                class="btn btn-sm btn-warning shadow-sm border-0"
                                            >
                                                Edit
                                            </router-link>
                                            <button
                                                @click="handleDelete(user.id)"
                                                :disabled="isPending"
                                                class="btn btn-sm btn-danger shadow-sm border-0"
                                            >
                                                {{
                                                    isPending
                                                        ? "Sedang menghapus..."
                                                        : "Hapus"
                                                }}
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>
