// frontend-vue-ts/src/views/admin/books/edit.vue
<script setup lang="ts">
//import ref, reactive dan watchEffect dari vue
import { ref, reactive, watchEffect } from "vue";

//import useRoute dan useRouter dari vue-router
import { useRoute, useRouter } from "vue-router";

//import component SidebarMenu
import SidebarMenu from "../../../components/SidebarMenu.vue";

//import composable useBookById
import { useBookById } from "../../../composables/book/useBookById";

//import composable useBookUpdate
import { useBookUpdate } from "../../../composables/book/useBookUpdate";

// inisialisasi route dan router
const route = useRoute();
const router = useRouter();

// Ambil ID dari route param
const id = Number(route.params.id);

// Form state
const title = ref<string>("");
const code = ref<string>("");
const author = ref<string>("");
const year = ref<number>(0);
const synapsis = ref<string>("");

// Validation errors
const errors = reactive<Record<string, string>>({});

// Fetch book by ID
const { data: book } = useBookById(id);

// Isi form dari data user
watchEffect(() => {
    if (book.value) {
        title.value = book.value.title;
        code.value = book.value.code;
        author.value = book.value.author;
        year.value = book.value.year;
        synapsis.value = book.value.synapsis;
    }
});

// Mutation
const { mutate, isPending } = useBookUpdate();

// Handle form submit
const updateBook = (e: Event) => {
    e.preventDefault();

    // Call user update mutation
    mutate(
        {
            id,
            data: {
                title: title.value,
                code: code.value,
                author: author.value,
                year: year.value,
                synapsis: synapsis.value,
            },
        },
        {
            onSuccess: () => {
                // Redirect to users index
                router.push("/admin/books");
            },
            onError: (error: any) => {
                // Assign validation errors to the errors object
                Object.assign(errors, error.response.data.errors);
            },
        }
    );
};
</script>

<template>
    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-md-3">
                <SidebarMenu />
            </div>
            <div class="col-md-9">
                <div class="card border-0 rounded-4 shadow-sm">
                    <div class="card-header">Edit User</div>
                    <div class="card-body">
                        <form @submit="updateBook">
                            <div class="form-group mb-3">
                                <label class="mb-1 fw-bold">Judul</label>
                                <input
                                    type="text"
                                    v-model="title"
                                    class="form-control"
                                    placeholder="Judul"
                                />
                                <div
                                    v-if="errors.Title"
                                    class="alert alert-danger mt-2"
                                >
                                    {{ errors.Title }}
                                </div>
                            </div>

                            <div class="form-group mb-3">
                                <label class="mb-1 fw-bold">Kode</label>
                                <input
                                    type="text"
                                    v-model="code"
                                    class="form-control"
                                    placeholder="Kode"
                                />
                                <div
                                    v-if="errors.Code"
                                    class="alert alert-danger mt-2"
                                >
                                    {{ errors.Code }}
                                </div>
                            </div>

                            <div class="form-group mb-3">
                                <label class="mb-1 fw-bold">Penulis</label>
                                <input
                                    type="text"
                                    v-model="author"
                                    class="form-control"
                                    placeholder="Penulis"
                                />
                                <div
                                    v-if="errors.Author"
                                    class="alert alert-danger mt-2"
                                >
                                    {{ errors.Author }}
                                </div>
                            </div>

                            <div class="form-group mb-3">
                                <label class="mb-1 fw-bold">Tahun</label>
                                <input
                                    type="number"
                                    v-model="year"
                                    class="form-control"
                                    placeholder="Tahun"
                                />
                                <div
                                    v-if="errors.Year"
                                    class="alert alert-danger mt-2"
                                >
                                    {{ errors.Year }}
                                </div>
                            </div>
                            <div class="form-group mb-3">
                                <label class="mb-1 fw-bold">Sinapsis</label>
                                <input
                                    type="text"
                                    v-model="synapsis"
                                    class="form-control"
                                    placeholder="Sinapsis"
                                />
                                <div
                                    v-if="errors.Synapsis"
                                    class="alert alert-danger mt-2"
                                >
                                    {{ errors.Synapsis }}
                                </div>
                            </div>
                            <div class="btn-group">
                                <button
                                    type="submit"
                                    class="btn btn-sm btn-primary shadow-sm border-0"
                                    :disabled="isPending"
                                >
                                    {{
                                        isPending
                                            ? "Sedang Menyimpan..."
                                            : "Simpan"
                                    }}
                                </button>

                                <router-link
                                    to="/admin/books"
                                    class="btn btn-sm btn-secondary shadow-sm border-0"
                                >
                                    Batal
                                </router-link>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

// frontend-react-ts/src/views/admin/books/edit.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
//import FC from react
import { type FC, useState, useEffect, type FormEvent } from "react";

//import SidebarMenu
import SidebarMenu from '../../../components/SidebarMenu';

//import useNavigate, useParams and Link from react-router
import { useNavigate, useParams, Link } from 'react-router';

//import custom hook useUserByById
import { useBookById } from '../../../hooks/book/useBookById';

//import custom hook useUserUpdate
import { useBookUpdate } from '../../../hooks/book/useBookUpdate';
import InputLabel from "../../../components/moleculles/InputLabel";
import ErrorAlert from "../../../components/moleculles/ErrorAlert";

//interface for validation errors
interface ValidationErrors {
    [key: string]: string;
}

const ProductEdit: FC = () => {

    //initialize useNavigate
    const navigate = useNavigate();

    //initialize useParams
    const { id } = useParams();

    //define state user
    const [title, setTitle] = useState<string>('');
    const [code, setCode] = useState<string>('');
    const [author, setAuthor] = useState<string>('');
    const [year, setYear] = useState<number>(0);
    const [synapsis, setSynapsis] = useState<string>('');

    //define state errors
    const [errors, setErrors] = useState<ValidationErrors>({});

    // inisialisasi useBookById
    const { data: book } = useBookById(Number(id));

    //set data user to state
    useEffect(() => {

        if (book) {
            setTitle(book.title);
            setCode(book.code);
            setAuthor(book.author);
            setYear(book.year);
            setSynapsis(book.synapsis);
        }
    }, [book]);

    // Inisialisasi useUserUpdate
    const { mutate, isPending } = useBookUpdate();

    // Handle submit form
    const updateBook = async (e: FormEvent) => {
        e.preventDefault();

        // Call the user update mutation
        mutate({
            id: Number(id),
            data: {
                title,
                code,
                author,
                year,
                synapsis
            }
        }, {
            onSuccess: () => {
                // Redirect to products index
                navigate('/admin/books');
            },
            onError: (error: any) => {
                //set errors to state "errors"
                setErrors(error.response.data.errors);
            }
        })
    }

    return (
        <div className="container mt-5 mb-5">
            <div className="row">
                <div className="col-md-3">
                    <SidebarMenu />
                </div>
                <div className="col-md-9">
                    <div className="card border-0 rounded-4 shadow-sm">
                        <div className="card-header">Ubah Data Buku</div>
                        <div className="card-body">
                            <form onSubmit={updateBook}>
                                <div className="form-group mb-3">
                                    <InputLabel htmlFor="title" label="Judul" isRequired={true} />
                                    <input type="text" value={title} id="name" onChange={(e) => setTitle(e.target.value)} className="form-control" placeholder="Judul" />
                                    {errors.Title && <ErrorAlert error={errors.Title} />}
                                </div>
                                <div className="form-group mb-3">
                                    <InputLabel htmlFor="code" label="Kode" isRequired={true} />
                                    <input type="text" value={code} id="code" onChange={(e) => setCode(e.target.value)} className="form-control" placeholder="Kode" />
                                    {errors.Code && <ErrorAlert error={errors.Code} />}
                                </div>
                                <div className="form-group mb-3">
                                    <InputLabel htmlFor="author" label="Penulis" isRequired={false} />
                                    <input type="text" value={author} id="author" onChange={(e) => setAuthor(e.target.value)} className="form-control" placeholder="Penulis" />
                                    {errors.Author && <ErrorAlert error={errors.Author} />}
                                </div>
                                <div className="form-group mb-3">
                                    <InputLabel htmlFor="year" label="Tahun" isRequired={false} />
                                    <input type="number" value={year} id="year" onChange={(e) => setYear(Number(e.target.value))} className="form-control" placeholder="Tahun" />
                                    {errors.Year && <ErrorAlert error={errors.Year} />}
                                </div>
                                <div className="form-group mb-3">
                                    <InputLabel htmlFor="synapsis" label="Sinapsis" isRequired={false} />
                                    <input type="text" value={synapsis} id="synapsis" onChange={(e) => setSynapsis(e.target.value)} className="form-control" placeholder="Sinapsis" />
                                    {errors.Synapsis && <ErrorAlert error={errors.Synapsis} />}
                                </div>
                                <div className="btn-group">
                                    <button type="submit" className="btn btn-sm btn-primary shadow-sm border-0" disabled={isPending}>
                                        {isPending ? 'Sedang Menyimpan...' : 'Simpan'}
                                    </button>
                                    <Link to="/admin/users" className="btn btn-sm btn-secondary shadow-sm border-0">Batal</Link>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div >
    )
}

export default ProductEdit
