// frontend-vue-ts/src/views/admin/books/index.vue
<script setup lang="ts">
//import useQueryClient dari '@tanstack/vue-query'
import { useQueryClient } from "@tanstack/vue-query";
// import composable useBooks
import { useBooks } from "../../../composables/book/useBooks";

// import composable useBookDelete
import { useBookDelete } from "../../../composables/book/useBookDelete";

// import SidebarMenu component
import SidebarMenu from "../../../components/SidebarMenu.vue";

// initialize query client
const queryClient = useQueryClient();

// Get books
const { data: books, isLoading, isError, error } = useBooks();

// // User delete composable
const { mutate, isPending } = useBookDelete();

// Handle delete
const handleDelete = (id: number) => {
    if (confirm("Are you sure you want to delete this book?")) {
        // Call delete user mutation
        mutate(id, {
            onSuccess: () => {
                // Invalidate users query to refresh the list
                queryClient.invalidateQueries({ queryKey: ["books"] });
            },
        });
    }
};
</script>

<template>
    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-md-3">
                <SidebarMenu />
            </div>
            <div class="col-md-9">
                <div class="card border-0 shadow-sm">
                    <div
                        class="card-header d-flex justify-content-between align-items-center"
                    >
                        <span>Data Buku</span>
                        <router-link
                            to="/admin/books/create"
                            class="btn btn-sm btn-primary shadow-sm border-0"
                        >
                            Tambah Data
                        </router-link>
                    </div>
                    <div class="card-body">
                        <div
                            v-if="isLoading"
                            class="alert alert-info text-center"
                        >
                            Loading...
                        </div>

                        <div
                            v-if="isError"
                            class="alert alert-danger text-center"
                        >
                            Error: {{ error?.message }}
                        </div>

                        <table v-if="books" class="table table-bordered">
                            <thead class="bg-dark text-white">
                                <tr>
                                    <th>Judul</th>
                                    <th>Kode</th>
                                    <th>Penulis</th>
                                    <th>Tahun</th>
                                    <th>Sinapsis</th>
                                    <th style="width: 20%">Opsi</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr v-for="book in books" :key="book.id">
                                    <td>{{ book.title }}</td>
                                    <td>{{ book.code }}</td>
                                    <td>{{ book.author }}</td>
                                    <td>{{ book.year }}</td>
                                    <td>{{ book.synapsis }}</td>
                                    <td class="text-center">
                                        <div class="btn-group">
                                            <router-link
                                                :to="`/admin/books/edit/${book.id}`"
                                                class="btn btn-sm btn-warning shadow-sm border-0"
                                            >
                                                Edit
                                            </router-link>
                                            <button
                                                @click="handleDelete(book.id)"
                                                :disabled="isPending"
                                                class="btn btn-sm btn-danger shadow-sm border-0"
                                            >
                                                {{
                                                    isPending
                                                        ? "Sedang menghapus..."
                                                        : "Hapus"
                                                }}
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

// frontend-react-ts/src/views/admin/books/index.tsx
//import FC from react
import { type FC } from "react";

//import SidebarMenu
import SidebarMenu from '../../../components/SidebarMenu';

//import Link from react-route
import { Link } from "react-router";

//import custom hook useUsers and interface User
import { useBooks, type Book } from "../../../hooks/book/useBooks";

import { useBookDelete } from "../../../hooks/book/useBookDelete";
import { useQueryClient } from "@tanstack/react-query";

const BooksIndex: FC = () => {

    // get books from useBooks
    const { data: books, isLoading, isError, error } = useBooks();

    const queryClient = useQueryClient();

    //initialize useUserDelete
    const { mutate, isPending } = useBookDelete();
    //handle delete user
    const handleDelete = (id: number) => {
        if (confirm("Are you sure you want to delete this book?")) {
            //call useUserDelete
            mutate(id, {
                onSuccess: () => {
                    //refetch data
                    queryClient.invalidateQueries({ queryKey: ['books'] });
                }
            });
        }
    }
    return (
        <div className="container mt-5 mb-5">
            <div className="row">
                <div className="col-md-3">
                    <SidebarMenu />
                </div>
                <div className="col-md-9">
                    <div className="card border-0 rounded-0 shadow-sm">
                        <div className="card-header d-flex justify-content-between align-items-center">
                            <span>Data Buku</span>
                            <Link to="/admin/books/create" className="btn btn-sm btn-primary shadow-sm border-0">Tambah Data</Link>
                        </div>
                        <div className="card-body">

                            {/* Loading State */}
                            {isLoading && (
                                <div className="alert alert-info text-center">Loading...</div>
                            )}

                            {/* Error State */}
                            {isError && (
                                <div className="alert alert-danger text-center">
                                    Error: {error.message}
                                </div>
                            )}

                            <table className="table table-bordered">
                                <thead className="bg-dark text-white">
                                    <tr>
                                        <th scope="col">Judul</th>
                                        <th scope="col">Kode</th>
                                        <th scope="col">Penulis</th>
                                        <th scope="col">Tahun</th>
                                        <th scope="col">Sinapsis</th>
                                        <th scope="col" style={{ width: "20%" }}>Opsi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {
                                        books?.map((object: Book) => (
                                            <tr key={object.id}>
                                                <td>{object.title}</td>
                                                <td>{object.code}</td>
                                                <td>{object.author}</td>
                                                <td>{object.year}</td>
                                                <td>{object.synapsis}</td>
                                                <td className="text-center">
                                                    <div className="btn-group">
                                                        <Link to={`/admin/books/edit/${object.id}`} className="btn btn-sm btn-primary shadow-sm border-0">Edit</Link>
                                                        <button onClick={() => handleDelete(object.id)} disabled={isPending} className="btn btn-sm btn-danger shadow-sm border-0">
                                                            {isPending ? 'Sedang Menghapus...' : 'Hapus'}
                                                        </button>
                                                    </div>
                                                </td>
                                            </tr>
                                        ))
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default BooksIndex
