// frontend-react-ts/src/components/SidebarMenu.tsx
//import FC from react
import { type FC } from "react";

//import Link from react router dom
import { Link } from "react-router";
import { useLogout } from "../hooks/auth/useLogout";

const SidebarMenu: FC = () => {
    const logout = useLogout();
    return (
        <div className="card border-0 rounded-0 shadow-sm">
            <div className="card-header">Menu</div>
            <div className="card-body rounded-0">
                <div className="list-group rounded-0">
                    <Link to="/admin/dashboard" className="list-group-item list-group-item-action">Dashboard</Link>
                    <Link to="/admin/users" className="list-group-item list-group-item-action">Data User</Link>
                    <Link to="/admin/books" className="list-group-item list-group-item-action">Data Buku</Link>
                    <a href="#" onClick={logout} className="list-group-item list-group-item-action" style={{ cursor: 'pointer' }}>Logout</a>
                </div>
            </div>
        </div>
    );
};

export default SidebarMenu;

// frontend-vue-ts/src/components/SidebarMenu.vue
<script setup lang="ts">
//import composable useLogout
import { useLogout } from "../composables/auth/useLogout";

//initialize useLogout
const logout = useLogout();
</script>

<template>
    <div class="card border-0 shadow-sm">
        <div class="card-header">Menu</div>
        <div class="card-body">
            <div class="list-group">
                <router-link
                    to="/admin/dashboard"
                    class="list-group-item list-group-item-action"
                    >Dashboard</router-link
                >
                <router-link
                    to="/admin/users"
                    class="list-group-item list-group-item-action"
                    >Data User</router-link
                >
                <router-link
                    to="/admin/books"
                    class="list-group-item list-group-item-action"
                    >Data Buku</router-link
                >
                <a
                    href="#"
                    @click="logout"
                    class="list-group-item list-group-item-action"
                    >Logout</a
                >
            </div>
        </div>
    </div>
</template>
