// frontend-vue-ts/src/App.vue
<script setup lang="ts"></script>

<template>
    <div>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <router-link :to="{ name: 'home' }" class="navbar-brand"
                    >Home</router-link
                >
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div
                    class="collapse navbar-collapse"
                    id="navbarSupportedContent"
                >
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a
                                href="https://codopro.id"
                                target="_blank"
                                class="nav-link active"
                                aria-current="page"
                                >codopro.id</a
                            >
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <!--- render router view -->
        <div class="container mt-5">
            <router-view></router-view>
        </div>
    </div>
</template>

// frontend-react-ts/src/App.tsx
// import FC from react
import type { FC } from 'react';

//import router
import AppRoutes from './routes';

//import Link from react router
import { Link } from "react-router";
import Logo from "./assets/logo.png";

const App: FC = () => {

  return (
    <div>
      <nav className="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
        <div className="container">
          <Link to="/" className="navbar-brand">
            <img src={Logo} className="img-fluid" style={{ height: 40 }} alt="Logo" />
          </Link>
          <button
            className="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span className="navbar-toggler-icon"></span>
          </button>
          <div className="collapse navbar-collapse" id="navbarSupportedContent">
            <ul className="navbar-nav ms-auto mb-2 mb-lg-0">
              <li className="nav-item">
                <a href="https://codopro.id" target="_blank" className="nav-link active" aria-current="page">CODOPRO.ID</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <div className="container mt-5">
        <AppRoutes />
      </div>
    </div>
  )
}

export default App;
