// frontend-vue-ts/src/views/admin/dashboard/index.vue
<script setup lang="ts">
//import sidebar component
import SidebarMenu from "../../../components/SidebarMenu.vue";

//import composable useAuthUser
import { useAuthUser } from "../../../composables/auth/useAuthUser";

//inisialisasi useAuthUser
const user = useAuthUser();
</script>

<template>
    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-md-3">
                <SidebarMenu />
            </div>
            <div class="col-md-9">
                <div class="card border-0 shadow-sm">
                    <div class="card-header">Dashboard</div>
                    <div class="card-body">
                        Selamat Datang, <strong>{{ user?.name }}</strong>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

// frontend-react-ts/src/views/admin/dashboard/index.tsx
//import FC from react
import { type FC } from "react";

//import SidebarMenu
import SidebarMenu from '../../../components/SidebarMenu';

//import custom hook useAuthUser
import { useAuthUser } from '../../../hooks/auth/useAuthUser';

const Dashboard: FC = () => {

    // get user from useAuthUser
    const user = useAuthUser();

    return (
        <div className="container mt-5 mb-5">
            <div className="row">
                <div className="col-md-3">
                    <SidebarMenu />
                </div>
                <div className="col-md-9">
                    <div className="card border-0 rounded-4 shadow-sm">
                        <div className="card-header">
                            DASHBOARD
                        </div>
                        <div className="card-body">
                            {user ? (
                                <p>Selamat datang, <strong>{user.name}</strong>!</p>
                            ) : (
                                <p>Kamu belum login.</p>
                            )}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    )
}

export default Dashboard
